### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by Telling** [Sec42/freebsd-remote-crypto#1]
Hello,

First off, great work on these scripts - they provide a nice insight into how to build such a system. However they're of limited use since there is [no license](https://choosealicense.com/no-permission/).

Would you consider adding a license?

**Comment by Sec42** [comment]
I somewhat doubt that these script cross the [threshold of originality](https://en.wikipedia.org/wiki/Threshold_of_originality) but I can add a license if it is deemed necessary.
