### ISSUE TITLE
How to update 

### ISSUE THREAD

**Issue by network-shark** [Sec42/freebsd-remote-crypto#2]
If I understand the setup correctly how can I setup the ufs partition ? Do I have to use freebsd-update -b pointing to the ufs file system ?

And in which order do you update the system ? I think I would start with the systems on the mirror and after that I would update the ufs partition ? 

thank you !

**Comment by Sec42** [comment]
All I usually do is run freebsd-update as normal (`freebsd-update fetch; freebsd-update install`).

Afterwards I run `sh PREBOOT update` as specified in the README to update the "preboot" environment. (which is mounted at /xboot in this setup)
