### ISSUE TITLE
fetch: CRYPT: open(): Read-only file system

### ISSUE THREAD

**Issue by NicholasBHubbard** [Sec42/freebsd-remote-crypto#5]
I boot into installation media, select shell, and run dhclient. This all goes fine.

Next when I go to fetch the scripts I get 
```
fetch: CRYPT: open(): Read-only file system
fetch: PREBOOT: open(): Read-only file system
```
I then cannot run `sh CRYPT`

**Comment by Sec42** [comment]
You need to run the two `fetch` lines while in a writable directory. Try `cd /tmp` before running them.

**Comment by NicholasBHubbard** [comment]
worked, thanks
